const cities = [{
    first: 'A',
    city: [{ code: '513200', name: '阿坝藏族羌族自治州', py: 'aba', sx: 'ab' },
    { code: '652900', name: '阿克苏地区', py: 'akesu', sx: 'aks' },
    { code: '152900', name: '阿拉善盟', py: 'alashan', sx: 'als' },
    { code: '654300', name: '阿勒泰地区', py: 'aletai', sx: 'alt' },
    { code: '542500', name: '阿里地区', py: 'ali', sx: 'al' },
    { code: '610900', name: '安康市', py: 'ankang', sx: 'ak' },
    { code: '340800', name: '安庆市', py: 'anqing', sx: 'aq' },
    { code: '520400', name: '安顺市', py: 'anshun', sx: 'as' },
    { code: '410500', name: '安阳市', py: 'anyang', sx: 'ay' },
    { code: '210300', name: '鞍山市', py: 'anshan', sx: 'as' },
    ]
},
{
    first: 'B',
    city: [{ code: '150800', name: '巴彦淖尔市', py: 'bayannaoer', sx: 'byne' },
    { code: '652800', name: '巴音郭楞蒙古自治州', py: 'bayinguoleng', sx: 'bygl' },
    { code: '511900', name: '巴中市', py: 'bazhong', sx: 'bz' },
    { code: '220800', name: '白城市', py: 'baicheng', sx: 'bc' },
    { code: '220600', name: '白山市', py: 'baishan', sx: 'bs' },
    { code: '620400', name: '白银市', py: 'baiyin', sx: 'by' },
    { code: '451000', name: '百色市', py: 'baise', sx: 'bs' },
    { code: '340300', name: '蚌埠市', py: 'bangbu', sx: 'bb' },
    { code: '150200', name: '包头市', py: 'baotou', sx: 'bt' },
    { code: '610300', name: '宝鸡市', py: 'baoji', sx: 'bj' },
    { code: '130600', name: '保定市', py: 'baoding', sx: 'bd' },
    { code: '530500', name: '保山市', py: 'baoshan', sx: 'bs' },
    { code: '450500', name: '北海市', py: 'beihai', sx: 'bh' },
    { code: '110100', name: '北京市', py: 'beijing', sx: 'bj' },
    { code: '210500', name: '本溪市', py: 'benxi', sx: 'bx' },
    { code: '520500', name: '毕节市', py: 'bijie', sx: 'bj' },
    { code: '371600', name: '滨州市', py: 'binzhou', sx: 'bz' },
    { code: '341600', name: '亳州市', py: 'bozhou', sx: 'bz' },
    { code: '652700', name: '博尔塔拉蒙古自治州', py: 'boertala', sx: 'betl' },
    ]
},
{
    first: 'C',
    city: [{ code: '130900', name: '沧州市', py: 'cangzhou', sx: 'cz' },
    { code: '542100', name: '昌都市', py: 'changdou', sx: 'cd' },
    { code: '652300', name: '昌吉回族自治州', py: 'changji', sx: 'cj' },
    { code: '430700', name: '常德市', py: 'changde', sx: 'cd' },
    { code: '320400', name: '常州市', py: 'changzhou', sx: 'cz' },
    { code: '220100', name: '长春市', py: 'changchun', sx: 'cc' },
    { code: '430100', name: '长沙市', py: 'changsha', sx: 'cs' },
    { code: '140400', name: '长治市', py: 'changzhi', sx: 'cz' },
    { code: '211300', name: '朝阳市', py: 'chaoyang', sx: 'cy' },
    { code: '445100', name: '潮州市', py: 'chaozhou', sx: 'cz' },
    { code: '431000', name: '郴州市', py: 'chenzhou', sx: 'cz' },
    { code: '510100', name: '成都市', py: 'chengdou', sx: 'cd' },
    { code: '130800', name: '承德市', py: 'chengde', sx: 'cd' },
    { code: '341700', name: '池州市', py: 'chizhou', sx: 'cz' },
    { code: '150400', name: '赤峰市', py: 'chifeng', sx: 'cf' },
    { code: '451400', name: '崇左市', py: 'chongzuo', sx: 'cz' },
    { code: '341100', name: '滁州市', py: 'chuzhou', sx: 'cz' },
    { code: '532300', name: '楚雄彝族自治州', py: 'chuxiong', sx: 'cx' },
    ]
},
{
    first: 'D',
    city: [{ code: '511700', name: '达州市', py: 'dazhou', sx: 'dz' },
    { code: '532900', name: '大理白族自治州', py: 'dali', sx: 'dl' },
    { code: '210200', name: '大连市', py: 'dalian', sx: 'dl' },
    { code: '230600', name: '大庆市', py: 'daqing', sx: 'dq' },
    { code: '140200', name: '大同市', py: 'datong', sx: 'dt' },
    { code: '232700', name: '大兴安岭地区', py: 'daxinganling', sx: 'dxal' },
    { code: '210600', name: '丹东市', py: 'dandong', sx: 'dd' },
    { code: '533100', name: '德宏傣族景颇族自治州', py: 'dehong', sx: 'dh' },
    { code: '510600', name: '德阳市', py: 'deyang', sx: 'dy' },
    { code: '371400', name: '德州市', py: 'dezhou', sx: 'dz' },
    { code: '533400', name: '迪庆藏族自治州', py: 'diqing', sx: 'dq' },
    { code: '621100', name: '定西市', py: 'dingxi', sx: 'dx' },
    { code: '441900', name: '东莞市', py: 'dongguan', sx: 'dg' },
    { code: '370500', name: '东营市', py: 'dongying', sx: 'dy' },
    ]
},
{
    first: 'E',
    city: [{ code: '150600', name: '鄂尔多斯市', py: 'eerduosi', sx: 'eeds' },
    { code: '420700', name: '鄂州市', py: 'ezhou', sx: 'ez' },
    { code: '422800', name: '恩施土家族苗族自治州', py: 'enshi', sx: 'es' },
    ]
},
{
    first: 'F',
    city: [{ code: '450600', name: '防城港市', py: 'fangchenggang', sx: 'fcg' },
    { code: '440600', name: '佛山市', py: 'foshan', sx: 'fs' },
    { code: '350100', name: '福州市', py: 'fuzhou', sx: 'fz' },
    { code: '210400', name: '抚顺市', py: 'fushun', sx: 'fs' },
    { code: '361000', name: '抚州市', py: 'fuzhou', sx: 'fz' },
    { code: '210900', name: '阜新市', py: 'fuxin', sx: 'fx' },
    { code: '341200', name: '阜阳市', py: 'fuyang', sx: 'fy' },
    ]
},
{
    first: 'G',
    city: [{ code: '623000', name: '甘南藏族自治州', py: 'gannan', sx: 'gn' },
    { code: '513300', name: '甘孜藏族自治州', py: 'ganzi', sx: 'gz' },
    { code: '360700', name: '赣州市', py: 'ganzhou', sx: 'gz' },
    { code: '640400', name: '固原市', py: 'guyuan', sx: 'gy' },
    { code: '511600', name: '广安市', py: 'guangan', sx: 'ga' },
    { code: '510800', name: '广元市', py: 'guangyuan', sx: 'gy' },
    { code: '440100', name: '广州市', py: 'guangzhou', sx: 'gz' },
    { code: '450800', name: '贵港市', py: 'guigang', sx: 'gg' },
    { code: '520100', name: '贵阳市', py: 'guiyang', sx: 'gy' },
    { code: '450300', name: '桂林市', py: 'guilin', sx: 'gl' },
    { code: '632600', name: '果洛藏族自治州', py: 'guoluo', sx: 'gl' },
    ]
},
{
    first: 'H',
    city: [{ code: '230100', name: '哈尔滨市', py: 'haerbin', sx: 'heb' },
    { code: '652200', name: '哈密地区', py: 'hami', sx: 'hm' },
    { code: '632200', name: '海北藏族自治州', py: 'haibei', sx: 'hb' },
    { code: '630200', name: '海东地区', py: 'haidong', sx: 'hd' },
    { code: '460100', name: '海口市', py: 'haikou', sx: 'hk' },
    { code: '632500', name: '海南藏族自治州', py: 'hainan', sx: 'hn' },
    { code: '632800', name: '海西蒙古族藏族自治州', py: 'haixi', sx: 'hx' },
    { code: '130400', name: '邯郸市', py: 'handan', sx: 'hd' },
    { code: '610700', name: '汉中市', py: 'hanzhong', sx: 'hz' },
    { code: '330100', name: '杭州市', py: 'hangzhou', sx: 'hz' },
    { code: '340100', name: '合肥市', py: 'hefei', sx: 'hf' },
    { code: '653200', name: '和田地区', py: 'hetian', sx: 'ht' },
    { code: '451200', name: '河池市', py: 'hechi', sx: 'hc' },
    { code: '441600', name: '河源市', py: 'heyuan', sx: 'hy' },
    { code: '371700', name: '菏泽市', py: 'heze', sx: 'hz' },
    { code: '451100', name: '贺州市', py: 'hezhou', sx: 'hz' },
    { code: '410600', name: '鹤壁市', py: 'hebi', sx: 'hb' },
    { code: '230400', name: '鹤岗市', py: 'hegang', sx: 'hg' },
    { code: '231100', name: '黑河市', py: 'heihe', sx: 'hh' },
    { code: '131100', name: '衡水市', py: 'hengshui', sx: 'hs' },
    { code: '430400', name: '衡阳市', py: 'hengyang', sx: 'hy' },
    { code: '532500', name: '红河哈尼族彝族自治州', py: 'honghe', sx: 'hh' },
    { code: '150100', name: '呼和浩特市', py: 'huhehaote', sx: 'hhht' },
    { code: '150700', name: '呼伦贝尔市', py: 'hulunbeier', sx: 'hlbe' },
    { code: '211400', name: '葫芦岛市', py: 'huludao', sx: 'hld' },
    { code: '330500', name: '湖州市', py: 'huzhou', sx: 'hz' },
    { code: '431200', name: '怀化市', py: 'huaihua', sx: 'hh' },
    { code: '320800', name: '淮安市', py: 'huaian', sx: 'ha' },
    { code: '340600', name: '淮北市', py: 'huaibei', sx: 'hb' },
    { code: '340400', name: '淮南市', py: 'huainan', sx: 'hn' },
    { code: '421100', name: '黄冈市', py: 'huanggang', sx: 'hg' },
    { code: '632300', name: '黄南藏族自治州', py: 'huangnan', sx: 'hn' },
    { code: '341000', name: '黄山市', py: 'huangshan', sx: 'hs' },
    { code: '420200', name: '黄石市', py: 'huangshi', sx: 'hs' },
    { code: '441300', name: '惠州市', py: 'huizhou', sx: 'hz' },
    ]
},
{
    first: 'J',
    city: [{ code: '230300', name: '鸡西市', py: 'jixi', sx: 'jx' },
    { code: '360800', name: '吉安市', py: 'jian', sx: 'ja' },
    { code: '220200', name: '吉林市', py: 'jilin', sx: 'jl' },
    { code: '370100', name: '济南市', py: 'jinan', sx: 'jn' },
    { code: '370800', name: '济宁市', py: 'jining', sx: 'jn' },
    { code: '230800', name: '佳木斯市', py: 'jiamusi', sx: 'jms' },
    { code: '330400', name: '嘉兴市', py: 'jiaxing', sx: 'jx' },
    { code: '620200', name: '嘉峪关市', py: 'jiayuguan', sx: 'jyg' },
    { code: '440700', name: '江门市', py: 'jiangmen', sx: 'jm' },
    { code: '410800', name: '焦作市', py: 'jiaozuo', sx: 'jz' },
    { code: '445200', name: '揭阳市', py: 'jieyang', sx: 'jy' },
    { code: '620300', name: '金昌市', py: 'jinchang', sx: 'jc' },
    { code: '330700', name: '金华市', py: 'jinhua', sx: 'jh' },
    { code: '210700', name: '锦州市', py: 'jinzhou', sx: 'jz' },
    { code: '140500', name: '晋城市', py: 'jincheng', sx: 'jc' },
    { code: '140700', name: '晋中市', py: 'jinzhong', sx: 'jz' },
    { code: '420800', name: '荆门市', py: 'jingmen', sx: 'jm' },
    { code: '421000', name: '荆州市', py: 'jingzhou', sx: 'jz' },
    { code: '360200', name: '景德镇市', py: 'jingdezhen', sx: 'jdz' },
    { code: '532801', name: '景洪市', py: 'jinghong', sx: 'jh' },
    { code: '360400', name: '九江市', py: 'jiujiang', sx: 'jj' },
    { code: '620900', name: '酒泉市', py: 'jiuquan', sx: 'jq' },
    ]
},
{
    first: 'K',
    city: [{ code: '653100', name: '喀什地区', py: 'kashen', sx: 'ks' },
    { code: '410200', name: '开封市', py: 'kaifeng', sx: 'kf' },
    { code: '650200', name: '克拉玛依市', py: 'kelamayi', sx: 'klmy' },
    { code: '653000', name: '克孜勒苏柯尔克孜自治州', py: 'kezilesu', sx: 'kzls' },
    { code: '530100', name: '昆明市', py: 'kunming', sx: 'km' },
    ]
},
{
    first: 'L',
    city: [{ code: '540100', name: '拉萨市', py: 'lasa', sx: 'ls' },
    { code: '451300', name: '来宾市', py: 'laibin', sx: 'lb' },
    { code: '371200', name: '莱芜市', py: 'laiwu', sx: 'lw' },
    { code: '620100', name: '兰州市', py: 'lanzhou', sx: 'lz' },
    { code: '131000', name: '廊坊市', py: 'langfang', sx: 'lf' },
    { code: '511100', name: '乐山市', py: 'leshan', sx: 'ls' },
    { code: '530700', name: '丽江市', py: 'lijiang', sx: 'lj' },
    { code: '331100', name: '丽水市', py: 'lishui', sx: 'ls' },
    { code: '320700', name: '连云港市', py: 'lianyungang', sx: 'lyg' },
    { code: '513400', name: '凉山彝族自治州', py: 'liangshan', sx: 'ls' },
    { code: '211000', name: '辽阳市', py: 'liaoyang', sx: 'ly' },
    { code: '220400', name: '辽源市', py: 'liaoyuan', sx: 'ly' },
    { code: '371500', name: '聊城市', py: 'liaocheng', sx: 'lc' },
    { code: '542600', name: '林芝市', py: 'linzhi', sx: 'lz' },
    { code: '530900', name: '临沧市', py: 'lincang', sx: 'lc' },
    { code: '141000', name: '临汾市', py: 'linfen', sx: 'lf' },
    { code: '622900', name: '临夏回族自治州', py: 'linxia', sx: 'lx' },
    { code: '371300', name: '临沂市', py: 'linyi', sx: 'ly' },
    { code: '450200', name: '柳州市', py: 'liuzhou', sx: 'lz' },
    { code: '341500', name: '六安市', py: 'liuan', sx: 'la' },
    { code: '520200', name: '六盘水市', py: 'liupanshui', sx: 'lps' },
    { code: '350800', name: '龙岩市', py: 'longyan', sx: 'ly' },
    { code: '621200', name: '陇南市', py: 'longnan', sx: 'ln' },
    { code: '431300', name: '娄底市', py: 'loudi', sx: 'ld' },
    { code: '510500', name: '泸州市', py: 'luzhou', sx: 'lz' },
    { code: '410300', name: '洛阳市', py: 'luoyang', sx: 'ly' },
    { code: '411100', name: '漯河市', py: 'luohe', sx: 'lh' },
    { code: '141100', name: '吕梁市', py: 'lu:liang', sx: 'll' },
    ]
},
{
    first: 'M',
    city: [{ code: '340500', name: '马鞍山市', py: 'maanshan', sx: 'mas' },
    { code: '440900', name: '茂名市', py: 'maoming', sx: 'mm' },
    { code: '511400', name: '眉山市', py: 'meishan', sx: 'ms' },
    { code: '441400', name: '梅州市', py: 'meizhou', sx: 'mz' },
    { code: '510700', name: '绵阳市', py: 'mianyang', sx: 'my' },
    { code: '231000', name: '牡丹江市', py: 'mudanjiang', sx: 'mdj' },
    ]
},
{
    first: 'N',
    city: [{ code: '542400', name: '那曲地区', py: 'neiqu', sx: 'nq' },
    { code: '360100', name: '南昌市', py: 'nanchang', sx: 'nc' },
    { code: '511300', name: '南充市', py: 'nanchong', sx: 'nc' },
    { code: '320100', name: '南京市', py: 'nanjing', sx: 'nj' },
    { code: '450100', name: '南宁市', py: 'nanning', sx: 'nn' },
    { code: '350700', name: '南平市', py: 'nanping', sx: 'np' },
    { code: '320600', name: '南通市', py: 'nantong', sx: 'nt' },
    { code: '411300', name: '南阳市', py: 'nanyang', sx: 'ny' },
    { code: '511000', name: '内江市', py: 'neijiang', sx: 'nj' },
    { code: '330200', name: '宁波市', py: 'ningbo', sx: 'nb' },
    { code: '350900', name: '宁德市', py: 'ningde', sx: 'nd' },
    { code: '533300', name: '怒江傈僳族自治州', py: 'nujiang', sx: 'nj' },
    ]
},
{
    first: 'P',
    city: [{ code: '510400', name: '攀枝花市', py: 'panzhihua', sx: 'pzh' },
    { code: '211100', name: '盘锦市', py: 'panjin', sx: 'pj' },
    { code: '410400', name: '平顶山市', py: 'pingdingshanp', sx: 'ds' },
    { code: '620800', name: '平凉市', py: 'pingliang', sx: 'pl' },
    { code: '360300', name: '萍乡市', py: 'pingxiang', sx: 'px' },
    { code: '350300', name: '莆田市', py: 'putian', sx: 'pt' },
    { code: '410900', name: '濮阳市', py: 'puyang', sx: 'py' },
    { code: '530800', name: '普洱市', py: 'puer', sx: 'pe' },
    ]
},
{
    first: 'Q',
    city: [{ code: '230900', name: '七台河市', py: 'qitaihe', sx: 'qth' },
    { code: '230200', name: '齐齐哈尔市', py: 'qiqihaer', sx: 'qqhe' },
    { code: '522600', name: '黔东南苗族侗族自治州', py: 'qiandongnan', sx: 'qdn' },
    { code: '522700', name: '黔南布依族苗族自治州', py: 'qiannan', sx: 'qn' },
    { code: '522300', name: '黔西南布依族苗族自治州', py: 'qianxinan', sx: 'qxn' },
    { code: '450700', name: '钦州市', py: 'qinzhou', sx: 'qz' },
    { code: '130300', name: '秦皇岛市', py: 'qinhuangdao', sx: 'qhd' },
    { code: '370200', name: '青岛市', py: 'qingdao', sx: 'qd' },
    { code: '441800', name: '清远市', py: 'qingyuan', sx: 'qy' },
    { code: '621000', name: '庆阳市', py: 'qingyang', sx: 'qy' },
    { code: '330800', name: '衢州市', py: 'quzhou', sx: 'qz' },
    { code: '530300', name: '曲靖市', py: 'qujing', sx: 'qj' },
    { code: '350500', name: '泉州市', py: 'quanzhou', sx: 'qz' },
    ]
},
{
    first: 'R',
    city: [{ code: '542300', name: '日喀则地区', py: 'rikaze', sx: 'rkz' },
    { code: '371100', name: '日照市', py: 'rizhao', sx: 'rz' },
    ]
},
{
    first: 'S',
    city: [{ code: '411200', name: '三门峡市', py: 'sanmenxia', sx: 'smx' },
    { code: '350400', name: '三明市', py: 'sanming', sx: 'sm' },
    { code: '460300', name: '三沙市', py: 'sansha', sx: 'ss' },
    { code: '460200', name: '三亚市', py: 'sanya', sx: 'sy' },
    { code: '542200', name: '山南地区', py: 'shannan', sx: 'sn' },
    { code: '440500', name: '汕头市', py: 'shantou', sx: 'st' },
    { code: '441500', name: '汕尾市', py: 'shanwei', sx: 'sw' },
    { code: '611000', name: '商洛市', py: 'shangluo', sx: 'sl' },
    { code: '411400', name: '商丘市', py: 'shangqiu', sx: 'sq' },
    { code: '310100', name: '上海市', py: 'shanghai', sx: 'sh' },
    { code: '361100', name: '上饶市', py: 'shangrao', sx: 'sr' },
    { code: '440200', name: '韶关市', py: 'shaoguan', sx: 'sg' },
    { code: '430500', name: '邵阳市', py: 'shaoyang', sx: 'sy' },
    { code: '330600', name: '绍兴市', py: 'shaoxing', sx: 'sx' },
    { code: '440300', name: '深圳市', py: 'shenzhen', sx: 'sz' },
    { code: '210100', name: '沈阳市', py: 'shenyang', sx: 'sy' },
    { code: '420300', name: '十堰市', py: 'shiyan', sx: 'sy' },
    { code: '130100', name: '石家庄市', py: 'shijiazhuang', sx: 'sjz' },
    { code: '640200', name: '石嘴山市', py: 'shizuishan', sx: 'szs' },
    { code: '230500', name: '双鸭山市', py: 'shuangyashan', sx: 'sys' },
    { code: '140600', name: '朔州市', py: 'shuozhou', sx: 'sz' },
    { code: '220300', name: '四平市', py: 'siping', sx: 'sp' },
    { code: '220700', name: '松原市', py: 'songyuan', sx: 'sy' },
    { code: '320500', name: '苏州市', py: 'suzhou', sx: 'sz' },
    { code: '231200', name: '绥化市', py: 'suihua', sx: 'sh' },
    { code: '321300', name: '宿迁市', py: 'suqian', sx: 'sq' },
    { code: '341300', name: '宿州市', py: 'suzhou', sx: 'sz' },
    { code: '421300', name: '随州市', py: 'suizhou', sx: 'sz' },
    { code: '510900', name: '遂宁市', py: 'suining', sx: 'sn' },
    ]
},
{
    first: 'T',
    city: [{ code: '654200', name: '塔城地区', py: 'tacheng', sx: 'tc' },
    { code: '331000', name: '台州市', py: 'taizhou', sx: 'tz' },
    { code: '140100', name: '太原市', py: 'taiyuan', sx: 'ty' },
    { code: '370900', name: '泰安市', py: 'taian', sx: 'ta' },
    { code: '321200', name: '泰州市', py: 'taizhou', sx: 'tz' },
    { code: '130200', name: '唐山市', py: 'tangshan', sx: 'ts' },
    { code: '120100', name: '天津市', py: 'tianjin', sx: 'tj' },
    { code: '620500', name: '天水市', py: 'tianshui', sx: 'ts' },
    { code: '211200', name: '铁岭市', py: 'tieling', sx: 'tl' },
    { code: '220500', name: '通化市', py: 'tonghua', sx: 'th' },
    { code: '150500', name: '通辽市', py: 'tongliao', sx: 'tl' },
    { code: '610200', name: '铜川市', py: 'tongchuan', sx: 'tc' },
    { code: '340700', name: '铜陵市', py: 'tongling', sx: 'tl' },
    { code: '520600', name: '铜仁地区', py: 'tongren', sx: 'tr' },
    { code: '652100', name: '吐鲁番地区', py: 'tulufan', sx: 'tlf' },
    ]
},
{
    first: 'W',
    city: [{ code: '371000', name: '威海市', py: 'weihai', sx: 'wh' },
    { code: '370700', name: '潍坊市', py: 'weifang', sx: 'wf' },
    { code: '610500', name: '渭南市', py: 'weinan', sx: 'wn' },
    { code: '330300', name: '温州市', py: 'wenzhou', sx: 'wz' },
    { code: '532600', name: '文山壮族苗族自治州', py: 'wenshan', sx: 'ws' },
    { code: '150300', name: '乌海市', py: 'wuhai', sx: 'wh' },
    { code: '150900', name: '乌兰察布市', py: 'wulanchab', sx: 'uwlcb' },
    { code: '650100', name: '乌鲁木齐市', py: 'wulumuqi', sx: 'wlmq' },
    { code: '320200', name: '无锡市', py: 'wuxi', sx: 'wx' },
    { code: '340200', name: '芜湖市', py: 'wuhu', sx: 'wh' },
    { code: '640300', name: '吴忠市', py: 'wuzhong', sx: 'wz' },
    { code: '450400', name: '梧州市', py: 'wuzhou', sx: 'wz' },
    { code: '420100', name: '武汉市', py: 'wuhan', sx: 'wh' },
    { code: '620600', name: '武威市', py: 'wuwei', sx: 'ww' },
    ]
},
{
    first: 'X',
    city: [{ code: '610100', name: '西安市', py: 'xian', sx: 'xa' },
    { code: '630100', name: '西宁市', py: 'xining', sx: 'xn' },
    { code: '532800', name: '西双版纳傣族自治州', py: 'xishuangbanna', sx: 'xsbn' },
    { code: '152500', name: '锡林郭勒盟', py: 'xilinguole', sx: 'xlgl' },
    { code: '350200', name: '厦门市', py: 'xiamen', sx: 'xm' },
    { code: '421200', name: '咸宁市', py: 'xianning', sx: 'xn' },
    { code: '610400', name: '咸阳市', py: 'xianyang', sx: 'xy' },
    { code: '430300', name: '湘潭市', py: 'xiangtan', sx: 'xt' },
    { code: '433100', name: '湘西土家族苗族自治州', py: 'xiangxi', sx: 'xx' },
    { code: '420600', name: '襄阳市', py: 'xiangyang', sx: 'xy' },
    { code: '420900', name: '孝感市', py: 'xiaogan', sx: 'xg' },
    { code: '140900', name: '忻州市', py: 'xinzhou', sx: 'xz' },
    { code: '410700', name: '新乡市', py: 'xinxiang', sx: 'xx' },
    { code: '360500', name: '新余市', py: 'xinyu', sx: 'xy' },
    { code: '411500', name: '信阳市', py: 'xinyang', sx: 'xy' },
    { code: '130500', name: '邢台市', py: 'xingtai', sx: 'xt' },
    { code: '152200', name: '兴安市', py: 'xingan', sx: 'xa' },
    { code: '320300', name: '徐州市', py: 'xuzhou', sx: 'xz' },
    { code: '411000', name: '许昌市', py: 'xuchang', sx: 'xc' },
    { code: '341800', name: '宣城市', py: 'xuancheng', sx: 'xc' },
    ]
},
{
    first: 'Y',
    city: [{ code: '511800', name: '雅安市', py: 'yaan', sx: 'ya' },
    { code: '370600', name: '烟台市', py: 'yantai', sx: 'yt' },
    { code: '610600', name: '延安市', py: 'yanan', sx: 'ya' },
    { code: '222400', name: '延边朝鲜族自治州', py: 'yanbian', sx: 'yb' },
    { code: '320900', name: '盐城市', py: 'yancheng', sx: 'yc' },
    { code: '321000', name: '扬州市', py: 'yangzhou', sx: 'yz' },
    { code: '441700', name: '阳江市', py: 'yangjiang', sx: 'yj' },
    { code: '140300', name: '阳泉市', py: 'yangquan', sx: 'yq' },
    { code: '230700', name: '伊春市', py: 'yichun', sx: 'yc' },
    { code: '654000', name: '伊犁哈萨克自治州', py: 'yili', sx: 'yl' },
    { code: '511500', name: '宜宾市', py: 'yibin', sx: 'yb' },
    { code: '420500', name: '宜昌市', py: 'yichang', sx: 'yc' },
    { code: '360900', name: '宜春市', py: 'yichun', sx: 'yc' },
    { code: '430900', name: '益阳市', py: 'yiyang', sx: 'yy' },
    { code: '640100', name: '银川市', py: 'yinchuan', sx: 'yc' },
    { code: '360600', name: '鹰潭市', py: 'yingtan', sx: 'yt' },
    { code: '210800', name: '营口市', py: 'yingkou', sx: 'yk' },
    { code: '431100', name: '永州市', py: 'yongzhou', sx: 'yz' },
    { code: '610800', name: '榆林市', py: 'yulin', sx: 'yl' },
    { code: '450900', name: '玉林市', py: 'yulin', sx: 'yl' },
    { code: '632700', name: '玉树藏族自治州', py: 'yushu', sx: 'ys' },
    { code: '530400', name: '玉溪市', py: 'yuxi', sx: 'yx' },
    { code: '430600', name: '岳阳市', py: 'yueyang', sx: 'yy' },
    { code: '445300', name: '云浮市', py: 'yunfu', sx: 'yf' },
    { code: '140800', name: '运城市', py: 'yuncheng', sx: 'yc' },
    ]
},
{
    first: 'Z',
    city: [{ code: '370400', name: '枣庄市', py: 'zaozhuang', sx: 'zz' },
    { code: '440800', name: '湛江市', py: 'zhanjiang', sx: 'zj' },
    { code: '430800', name: '张家界市', py: 'zhangjiajie', sx: 'zjj' },
    { code: '130700', name: '张家口市', py: 'zhangjiakou', sx: 'zjk' },
    { code: '620700', name: '张掖市', py: 'zhangye', sx: 'zy' },
    { code: '350600', name: '漳州市', py: 'zhangzhou', sx: 'zz' },
    { code: '530600', name: '昭通市', py: 'zhaotong', sx: 'zt' },
    { code: '441200', name: '肇庆市', py: 'zhaoqing', sx: 'zq' },
    { code: '321100', name: '镇江市', py: 'zhenjiang', sx: 'zj' },
    { code: '410100', name: '郑州市', py: 'zhengzhou', sx: 'zz' },
    { code: '442000', name: '中山市', py: 'zhongshan', sx: 'zs' },
    { code: '640500', name: '中卫市', py: 'zhongwei', sx: 'zw' },
    { code: '500100', name: '重庆市', py: 'zhongqing', sx: 'zq' },
    { code: '330900', name: '舟山市', py: 'zhoushan', sx: 'zs' },
    { code: '411600', name: '周口市', py: 'zhoukou', sx: 'zk' },
    { code: '440400', name: '珠海市', py: 'zhuhai', sx: 'zh' },
    { code: '430200', name: '株洲市', py: 'zhuzhou', sx: 'zz' },
    { code: '411700', name: '驻马店市', py: 'zhumadianz', sx: 'md' },
    { code: '512000', name: '资阳市', py: 'ziyang', sx: 'zy' },
    { code: '370300', name: '淄博市', py: 'zibo', sx: 'zb' },
    { code: '510300', name: '自贡市', py: 'zigong', sx: 'zg' },
    { code: '520300', name: '遵义市', py: 'zunyi', sx: 'zy' },
    ]
}
];

module.exports = cities;